services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install --production
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://osamagivegh:990099@cluster0.npzs81o.mongodb.net/portfolio?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://osamaportfolio.vercel.app

databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio_user
