services:
  - type: web
    name: portfolio-fullstack
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://osamagivegh:990099@cluster0.npzs81o.mongodb.net/portfolio?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://portfolio-fullstack.onrender.com

databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio_user
